// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skggqeszonovdqrtqmqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrZ2dxZXN6b25vdmRxcnRxbXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDcwNDksImV4cCI6MjA2Mjc4MzA0OX0.EFO1zw56j4S-0uLoR44m6NGDGb-n3dkysQb9lBJQ1e4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);